# Generated by Django 6.0.5 on 2026-05-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование скидки')),
                ('percent', models.PositiveIntegerField(verbose_name='Процент скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model_name', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Стоимость автомобиля')),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Суточная стоимость проката')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_5.cartype', verbose_name='Тип кузова')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('discounts', models.ManyToManyField(blank=True, to='lab_5.discount', verbose_name='Скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField(verbose_name='Дата выдачи')),
                ('days_count', models.PositiveIntegerField(verbose_name='Количество дней проката')),
                ('return_date', models.DateField(verbose_name='Ожидаемая дата возврата')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма проката')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_5.car', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_5.client', verbose_name='Клиент')),
            ],
        ),
    ]
